version: '3.7'

services:
  local-s3:
    image: minio/minio:RELEASE.2020-07-13T18-09-56Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: s3_access
      MINIO_SECRET_KEY: s3_secret
    entrypoint: sh
    command: -c 'mkdir -p /data/audio_input && minio server /data'
    volumes:
      - 'minio_data:/data'
    
  app:
    depends_on:
      - local-s3
    build: ./
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm test
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - TRANSCRIPTION_ENDPOINT=${TRANSCRIPTION_ENDPOINT}

volumes:
  minio_data:
    driver: local
